INSERT INTO aluno (matricula, nome, turma) VALUES ('000607','ANA CLARA BARBOSA MIRANDA','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000677','ERICK AUGUSTO CARDOSO SILVA','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000588','KAUA HENRIQUE FERNANDES OLIVEIRA','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000690','LAURA MARCIA ROCHA','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000674','LUCAS HENRIQUE FERREIRA ANTUNES','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000586','MARIA LUIZA MARTINS RIBEIRO','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000676','MIGUEL DE OLIVEIRA MARQUES','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000663','NICOLLY VILLANO TAVARES CHAGAS','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000661','SARA FRANCA RODRIGUES','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000622','GUILHERME AUGUSTO ALMEIDA SANTOS','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000713','MAYSA VITORIA MARTINS PEREIRA','1 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000709','ALICIA ISABELLE SOARES ALMEIDA','1 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000702','CAUA RIBEIRO DE PAULA','1 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000692','GIOVANA FERRAZ DINIZ','1 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000635','GUILHERME FERNANDO OLIVEIRA SILVA','1 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000705','SOFIA SEIXAS CORREA DE OLIVEIRA','1 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000350','ALICE BEATRIZ CASTRO DE SOUZA','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000369','ALICIA FERREIRA MENDES','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000356','CAROLINE COSTA LIRA','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000354','EMELY KELLE OLIVEIRA FELICIANO','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000386','EVELLY SOFIA MACHADO GONCALVES LEITE','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000353','EVELYN ELIANE OLIVEIRA FELICIANO','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000376','JULIA CAMPELO DA SILVA','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000364','KATHLEEN CRISTINE SOARES DOS SANTOS','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000418','KIARA YASMIM FERREIRA MONTEIRO','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000346','LUIS FELIPE DE BARROS SILVA','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000359','MIGUEL FALCAO ROCHA','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000349','PEDRO ROBERTO SILVA OLIVEIRA','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000362','YASMIM GABRIELLY ABREU DOS SANTOS','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000365','LAURA BEATRIZ MARINHO DE SOUZA','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000456','SAMUEL ALVES AQUINO','2 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000355','BRENDA NATALLY TOLENTINO DE OLIVEIRA','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000384','EMANUELLY DA SILVA RIBEIRO','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000383','ESTER FERREIRA SILVA','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000340','JUAN PABLO BRAGA BARBOSA','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000379','JULIA REBECA RIBEIRO DE PAULA','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000339','LAURA ARAUJO FREITAS','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000334','VINICIUS HENRIQUE COSTA SILVA','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000328','YASMIN HELENA RIBEIRO FELIX DIAS','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000352','CAMILA LORRANY CAMPOS LESSA','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000438','MARCELO HENRIQUE NUNES DE SOUZA','2 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000071','ANA LUIZA CASTRO DE SOUZA','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000290','GUSTAVO OLIVEIRA DE FREITAS','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000218','JOAO LUCAS SILVA COELHO','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000299','JOAO PEDRO GOMES DA COSTA','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000213','LUIS FELIPE SOARES DE ABREU','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000253','LUIS OTAVIO SOARES CARNEIRO','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000258','MARIA CLARA MARCAL TAVARES','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000260','MARIA EDUARDA MARCAL TAVARES','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000255','MARIA EDUARDA PAIVA LIMA','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000138','MAYCK WILLIAN SOARES PONCIANO DA SILVA','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000252','PAULO AFONSO AVELAR REIS','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000182','PRISCILA MIRANDA OLIVEIRA','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000264','VICTOR MARQUES DE PAULA','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000224','VITOR DE OLIVEIRA FREITAS','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000124','IASMIN ELSTNER RODRIGUES','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000302','LAZARO JUNIO FERREIRA NASCIMENTO','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000152','MARCUS EDUARDO SILVA ALMEIDA DOS SANTOS','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000038','PEDRO GABRIEL ALMEIDA SANTOS','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000351','RAFAELA BRANDAO SANTIAGO','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000024','MATHEUS AVELAR OLIVEIRA','3 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000130','ALICE ALVES CABRAL','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000107','ANA JULIA ARAUJO BRANDAO','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000291','BARBARA DE LIMA SILVA','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000036','KAUA LEANDRO GOMES DA SILVA','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000163','SARAH LETICIA DUTRA SOARES CORREA','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000193','VICTOR LUCKA RODRIGUES','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000202','WAGNER DE ALMEIDA BARBOSA JENIOR','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000232','ANA CLARA DE SOUZA SILVA','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000281','MARCIO GABRIEL BARBOSA POLICARPO','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000068','DANIELLY FERREIRA DOS SANTOS','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('0000343','BRUNA GABRIELA ALVES CAMPOS','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000087','ARTHUR GOMES SILVA','3 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000251','ANA LUIZA VIEIRA DA SILVA','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000237','BRUNO HENRIQUE MARTINS COSTA','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000288','JESSICA OLIVEIRA CARNEIRO','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000259','MARIA EDUARDA SILVA MAIA','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000250','YURI COSTA MARQUES RIBEIRO','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000267','LUCAS KAUA FERREIRA MONTEIRO','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000104','RENAN SANTOS LOPES','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000125','SAN-DIEGO MACIEL MARTINS','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000028','RAFAEL MARINHO DE SOUZA','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000573','MARCO TELIO TEIXEIRA DE ANDRADE','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000156','PAMELA LETICIA MARTINS MIRANDA','4 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000261','ANA CLARA CAETANO BARBOSA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000166','ANA JULIA ABREU GONCALVES','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000256','ANDRY HENRIQUE SIQUEIRA BARBOSA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000019','BIANCA DE ANDRADE JALES','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000140','FRANCISCO NEVES NAVARRO DE OLIVEIRA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000236','JOANA DARC ALVES DE SOUZA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000272','JOAO PEDRO MIRANDA DE SOUZA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000257','KAROLYNE APARECIDA FERREIRA DOS SANTOS','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000215','KAUE RIBEIRO FELIX DIAS','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000161','LUCAS RAFAEL MOREIRA DA SILVA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000183','MARIA EDUARDA LOPES MOURA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000315','RANGEL SARAIVA BRAGA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000316','ISADORA PIETRA OLIVEIRA CHAGAS','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000133','VICTOR RODRIGUES FIGUEIREDO','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000046','GUILHERME LIMA DE SOUZA CHAVES','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000018','SAMUEL WILLIAM ALVES DE SOUZA','4 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000247','ANA CAROLINA DE BARROS SILVA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000108','GABRIEL JUNIO MACIEL LIMA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000012','LUIZ OTAVIO DE LIMA GONCALVES','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000214','MARIA PAULA SILVA DO CARMO','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000321','RAFAEL VIEIRA SILVA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000304','SAMUEL COUTINHO PEREIRA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000249','CAIO HENRIQUE FERREIRA REIS','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000248','JULLIA CASSIANE VEIGA SILVA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000039','RIAN WENDER DE SOUZA SILVA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000262','SAMUEL BARBOSA DA SILVA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000147','VIVIANE CRISTINA TOMAZ TEIXEIRA','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000055','LUIS OTAVIO PEREIRA DA CONCEICAO','5 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000323','ALINE BARBOSA MOREIRA','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000314','ANNA JULIA VALADARES DE OLIVEIRA','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000298','JOAO VITOR CORREA DA SILVA','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000210','KAUAN MACHADO FREITAS','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000173','KAUANE GABRIELE ALVES COSTA','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000159','PIETRA GONCALVES SATURNINO','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000205','YASMIN JULIA DE CARVALHO PEREIRA','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000015','EMILY VITORIA COELHO CARVALHO','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000033','CARLA JASMIM DE LIMA SILVA','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000044','LETICIA LIMA DE SOUZA CHAVES','5 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000110','ANA CAROLINA GUILHERME DE SOUZA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000093','ANDREZA GONCALVES DA SILVA LIMA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000131','DANIELLA DAFNE OLIVEIRA FELICIANO','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000300','DANILO SILVA MOREIRA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000310','GRAZIELLA ARAEJO MENDES','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000285','LIS STEFANY DA COSTA DINIZ','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000313','LORENA VITORIA DOS SANTOS COELHO','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000233','LUCAS BARBOSA TORRES','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000097','MARCELA PEREIRA TEIXEIRA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000282','NETHALY DE JESUS GONCALVES','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000303','VINICIUS EDUARDO DA SILVA E ROSA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000188','ARTHUR EDUARDO GONCALVES SANTOS','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000275','CECILIA NYCOLLE RIBEIRO SOUZA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000266','ERIK FABIEL FERREIRA MONTEIRO','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000146','GUILHERME HENRIQUE MERCES LOURENCO','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000217','KAIQUE A‚NGELO MARQUES DE SOUZA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000307','LUCAS ARAUJO OLIVEIRA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000191','MARCUS VINICIUS FREITAS SOARES','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000312','PABLO EDUARDO TEIXEIRA RODRIGUES','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000220','VITORIA ISABELLE RODRIGUES DE ALMEIDA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000286','ANA LUIZA SILVA PEREIRA','6 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000279','DAVID MIGUEL ALMEIDA MARQUES SILVEIRA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000069','DANIEL AUGUSTO BARBOSA DA SILVA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000284','EDUARDA MARTINS DE SOUZA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000092','ERIK NUNES MACHADO','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000204','GIOVANNA EMANUELLE RODRIGUES DE OLIVEIRA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000296','JOAO VICTOR DE OLIVEIRA COSTA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000271','MARINA CAETANO CHAGAS','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000268','MAURO PATRICK FERREIRA RODRIGUES','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000187','OTAVIO MIRANDA OLIVEIRA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000185','PEDRO HENRIQUE ALEXANDRE SILVA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000222','RAYSSA ANTONIA DOS REIS ARAEJO','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000203','YASMIN LUANE DE OLIVEIRA CARDOSO','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000276','DAVI ELIAS MARTINS SILVA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000306','EDUARDO MARQUES BONFIM','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000127','JOHNNY ALVES DE OLIVEIRA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000123','MARIA CLARA DE PAULA VIEIRA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000225','TAYNARA ALINE GOMES DOS SANTOS','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000034','RAISSA BIANCA BARBOSA DA SILVA','6 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000231','LUANA BARBOSA TORRES','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000270','MARCUS CLAUDIO FERNANDES DE OLIVEIRA GOULART','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000139','MARIA EDUARDA VIEIRA MARCAL','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000168','MATHEUS HENRIQUE DA COSTA BALDEZ','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000117','NATALIA PEREIRA DE ALMEIDA','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000230','GABRIELLE VIEIRA SILVA','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000199','JULIA LARA SILVA VIDA','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000030','RAFAEL AVELAR OLIVEIRA','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000031','GABRIEL MARINHO DE SOUZA','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000043','LUIS FILIPE ALVES AQUINO','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000551','WENDER MATEUS PEREIRA DE OLIVEIRA','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000623','ANNA GABRIELLE COSTA RODRIGUES TOME','7 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000277','CRISTIELE LOPES GONCALVES RESENDE','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000283','DEBORA EDUARDA DOS SANTOS BARBOSA','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000129','LARISSA SOARES MENDES','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000311','LEONARDO SILVA GONCALVES','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000136','LUISA GOMES OLIVEIRA','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000308','MARIA EDUARDA DA SILVA','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000189','MARIA ELOISA DE OLIVEIRA CHAGAS','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000305','PEDRO LUIS GONCALVES DOMINGOS','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000032','RAYSSA MIRANDA SANTOS','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000320','MARIA EDUARDA DA COSTA DIAS','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000309','MARIA LUIZA RATES LOUZADA BARBOSA','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000272','VICTOR SAMUEL LACERDA RODRIGUES','7 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000516','PEDRO HENRIQUE SOARES CARNEIRO','8 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000409','ANDRE LUIS MARTINS MAIA','8 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000417','GIOVANNA DE OLIVEIRA LIMA','8 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000416','LAYSA EDUARDA OLIMPIO SOARES','8 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000400','ANA CLARA GOMES OLIVEIRA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000566','ANA LUiSA DE CARVALHO SILVEIRA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000423','GABRIEL HENRIQUE MOURA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000407','GIOVANNA ISABELLE DE OLIVEIRA CARDOSO','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000452','GUSTAVO HENRIQUE ARAEJO','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000487','HELIK CORDEIRO COSTA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000426','KAUA GABRIEL MAGALHAES BUERI MARTINS','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000432','PEDRO HENRIQUE MENDES DA SILVA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000570','CAMILA ALESSANDRA DUARTE','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000631','KEYSSE PRISCILA OLIVEIRA SILVA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000425','SAMUEL FERNANDES FERREIRA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000477','MARCOS LIMA FARIA','8 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000476','ANA CLARA DE LIMA SERRA BARRENSE','9 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000446','ISABELLA DE AZEVEDO COELHO','9 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000473','PAOLA VATOR RODRIGUES','9 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000457','GIOVANNA LETACIA TEIXEIRA DOS SANTOS','9 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000454','ANNA JULIA ALVES AQUINO','9 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000545','JOAO PAULO LAWALL COSTA','9 ANO A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000564','ARTHUR EDUARDO SILVA ALVES','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000550','CAIO CAMPOS VALADARES','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000527','FRANCIELE LOPES GONCALVES RESENDE','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000565','JOAO ROBERTO PEREIRA DOS REIS','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000435','LISLEY EDUARDA DA SILVA OLIVEIRA','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000559','LUAN BARBOSA SILVA CUNHA','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000483','LUANA DE CASSIA REIS GOMES','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000429','SARA EMANUELE SILVA MARQUES','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000493','ARTHUR HENRIQUE MORAIS COSTA','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000492','RANIELL LURRANE DOS REIS FLOR','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000439','VITORIA LUIZA SILVA SANTOS','9 ANO B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000505','KEROLLAY ALVES SANTIAGO','1a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000547','PEDRO PAULO NASCIMENTO JUNIOR','1a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000648','BEATRIZ SANTOS DE ALMEIDA','1a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000567','CARLA QUIRINA PEREIRA','1a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000537','GABRIEL TEIXEIRA ALVARENGA','1a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000499','JOAO PAULO WAGNER MONTEIRO DO AMARAL','1a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000489','PATRICK DIAS LOPES','1a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000513','JOAO GUILHERME GOMES DE PAULA','1a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000555','CAROLINA CARDOSO SOARES','1a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000436','EDUARDO JENIO SILVA SANTOS','1a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000533','LETHACIA GONCALVES MARTINS','1a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000518','DANIEL OLIVEIRA DE FARIA','1a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000723','CLARA GOMES ASSIS','2a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000706','MACLAUS CAMPOS CELESTINO','2a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000703','LETACIA APARECIDA MACHADO VIEIRA','2a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000739','MARCO ANTA”NIO DE SOUZA LOPES','2a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000626','JENNIFER BRENDA COSTA RODRIGUES TOME','2a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000725','ANA CAROLINA OLIVEIRA DA SILVA','3a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000749','JULIA SILVA MAXIMO','3a SERIE A');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000643','ANA CAROLINA LOURENCO MALTHIK','3a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000721','MARIA EDUARDA RODRIGUES PINHO','3a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000656','NATALIA MATOS DE OLIVEIRA','3a SERIE B');
INSERT INTO aluno (matricula, nome, turma) VALUES ('000628','STEPHANY CAROLINE COSTA RODRIGUES TOME','3a SERIE B');