update aluno set nome = 'ANA CLARA BARBOSA MIRANDA' where matricula - 000607 = 0;
update aluno set nome = 'ERICK AUGUSTO CARDOSO SILVA' where matricula - 000677 = 0;
update aluno set nome = 'KAUÃ HENRIQUE FERNANDES OLIVEIRA' where matricula - 000588 = 0;
update aluno set nome = 'LAURA MÁRCIA ROCHA' where matricula - 000690 = 0;
update aluno set nome = 'LUCAS HENRIQUE FERREIRA ANTUNES' where matricula - 000674 = 0;
update aluno set nome = 'MARIA LUIZA MARTINS RIBEIRO' where matricula - 000586 = 0;
update aluno set nome = 'MIGUEL DE OLIVEIRA MARQUES' where matricula - 000676 = 0;
update aluno set nome = 'NICOLLY VILLANO TAVARES CHAGAS' where matricula - 000663 = 0;
update aluno set nome = 'SARA FRANÇA RODRIGUES' where matricula - 000661 = 0;
update aluno set nome = 'GUILHERME AUGUSTO ALMEIDA SANTOS' where matricula - 000622 = 0;
update aluno set nome = 'MAYSA VITÓRIA MARTINS PEREIRA' where matricula - 000713 = 0;
update aluno set nome = 'ALICIA ISABELLE SOARES ALMEIDA' where matricula - 000709 = 0;
update aluno set nome = 'CAUÃ RIBEIRO DE PAULA' where matricula - 000702 = 0;
update aluno set nome = 'GIOVANA FERRAZ DINIZ' where matricula - 000692 = 0;
update aluno set nome = 'GUILHERME FERNANDO OLIVEIRA SILVA' where matricula - 000635 = 0;
update aluno set nome = 'SOFIA SEIXAS CORRÊA DE OLIVEIRA' where matricula - 000705 = 0;
update aluno set nome = 'ALICE BEATRIZ CASTRO DE SOUZA' where matricula - 000350 = 0;
update aluno set nome = 'ALICIA FERREIRA MENDES' where matricula - 000369 = 0;
update aluno set nome = 'CAROLINE COSTA LIRA' where matricula - 000356 = 0;
update aluno set nome = 'EMELY KELLE OLIVEIRA FELICIANO' where matricula - 000354 = 0;
update aluno set nome = 'EVELLY SOFIA MACHADO GONÇALVES LEITE' where matricula - 000386 = 0;
update aluno set nome = 'EVELYN ELIANE OLIVEIRA FELICIANO' where matricula - 000353 = 0;
update aluno set nome = 'JULIA CAMPELO DA SILVA' where matricula - 000376 = 0;
update aluno set nome = 'KATHLEEN CRISTINE SOARES DOS SANTOS' where matricula - 000364 = 0;
update aluno set nome = 'KIARA YASMIM FERREIRA MONTEIRO' where matricula - 000418 = 0;
update aluno set nome = 'LUIS FELIPE DE BARROS SILVA' where matricula - 000346 = 0;
update aluno set nome = 'MIGUEL FALCÃO ROCHA' where matricula - 000359 = 0;
update aluno set nome = 'PEDRO ROBERTO SILVA OLIVEIRA' where matricula - 000349 = 0;
update aluno set nome = 'YASMIM GABRIELLY ABREU DOS SANTOS' where matricula - 000362 = 0;
update aluno set nome = 'LAURA BEATRIZ MARINHO DE SOUZA' where matricula - 000365 = 0;
update aluno set nome = 'SAMUEL ALVES AQUINO' where matricula - 000456 = 0;
update aluno set nome = 'BRENDA NATALLY TOLENTINO DE OLIVEIRA' where matricula - 000355 = 0;
update aluno set nome = 'EMANUELLY DA SILVA RIBEIRO' where matricula - 000384 = 0;
update aluno set nome = 'ESTER FERREIRA SILVA' where matricula - 000383 = 0;
update aluno set nome = 'JUAN PABLO BRAGA BARBOSA' where matricula - 000340 = 0;
update aluno set nome = 'JÚLIA REBECA RIBEIRO DE PAULA' where matricula - 000379 = 0;
update aluno set nome = 'LAURA ARAUJO FREITAS' where matricula - 000339 = 0;
update aluno set nome = 'VINÍCIUS HENRIQUE COSTA SILVA' where matricula - 000334 = 0;
update aluno set nome = 'YASMIN HELENA RIBEIRO FELIX DIAS' where matricula - 000328 = 0;
update aluno set nome = 'CAMILA LORRANY CAMPOS LESSA' where matricula - 000352 = 0;
update aluno set nome = 'MARCELO HENRIQUE NUNES DE SOUZA' where matricula - 000438 = 0;
update aluno set nome = 'ANA LUIZA CASTRO DE SOUZA' where matricula - 000071 = 0;
update aluno set nome = 'GUSTAVO OLIVEIRA DE FREITAS' where matricula - 000290 = 0;
update aluno set nome = 'JOÃO LUCAS SILVA COELHO' where matricula - 000218 = 0;
update aluno set nome = 'JOÃO PEDRO GOMES DA COSTA' where matricula - 000299 = 0;
update aluno set nome = 'LUIS FELIPE SOARES DE ABREU' where matricula - 000213 = 0;
update aluno set nome = 'LUIS OTAVIO SOARES CARNEIRO' where matricula - 000253 = 0;
update aluno set nome = 'MARIA CLARA MARÇAL TAVARES' where matricula - 000258 = 0;
update aluno set nome = 'MARIA EDUARDA MARÇAL TAVARES' where matricula - 000260 = 0;
update aluno set nome = 'MARIA EDUARDA PAIVA LIMA' where matricula - 000255 = 0;
update aluno set nome = 'MAYCK WILLIAN SOARES PONCIANO DA SILVA' where matricula - 000138 = 0;
update aluno set nome = 'PAULO AFONSO AVELAR REIS' where matricula - 000252 = 0;
update aluno set nome = 'PRISCILA MIRANDA OLIVEIRA' where matricula - 000182 = 0;
update aluno set nome = 'VICTOR MARQUES DE PAULA' where matricula - 000264 = 0;
update aluno set nome = 'VITOR DE OLIVEIRA FREITAS' where matricula - 000224 = 0;
update aluno set nome = 'IASMIN ELSTNER RODRIGUES' where matricula - 000124 = 0;
update aluno set nome = 'LÁZARO JUNIO FERREIRA NASCIMENTO' where matricula - 000302 = 0;
update aluno set nome = 'MARCUS EDUARDO SILVA ALMEIDA DOS SANTOS' where matricula - 000152 = 0;
update aluno set nome = 'PEDRO GABRIEL ALMEIDA SANTOS' where matricula - 000038 = 0;
update aluno set nome = 'RAFAELA BRANDÃO SANTIAGO' where matricula - 000351 = 0;
update aluno set nome = 'MATHEUS AVELAR OLIVEIRA' where matricula - 000024 = 0;
update aluno set nome = 'ALICE ALVES CABRAL' where matricula - 000130 = 0;
update aluno set nome = 'ANA JULIA ARAUJO BRANDÃO' where matricula - 000107 = 0;
update aluno set nome = 'BÁRBARA DE LIMA SILVA' where matricula - 000291 = 0;
update aluno set nome = 'KAUÃ LEANDRO GOMES DA SILVA' where matricula - 000036 = 0;
update aluno set nome = 'SARAH LETÍCIA DUTRA SOARES CORRÊA' where matricula - 000163 = 0;
update aluno set nome = 'VICTOR LUCKA RODRIGUES' where matricula - 000193 = 0;
update aluno set nome = 'WAGNER DE ALMEIDA BARBOSA JÚNIOR' where matricula - 000202 = 0;
update aluno set nome = 'ANA CLARA DE SOUZA SILVA' where matricula - 000232 = 0;
update aluno set nome = 'MÁRCIO GABRIEL BARBOSA POLICARPO' where matricula - 000281 = 0;
update aluno set nome = 'DANIELLY FERREIRA DOS SANTOS' where matricula - 000068 = 0;
update aluno set nome = 'BRUNA GABRIELA ALVES CAMPOS' where matricula - 0000343 = 0;
update aluno set nome = 'ARTHUR GOMES SILVA' where matricula - 000087 = 0;
update aluno set nome = 'ANA LUIZA VIEIRA DA SILVA' where matricula - 000251 = 0;
update aluno set nome = 'BRUNO HENRIQUE MARTINS COSTA' where matricula - 000237 = 0;
update aluno set nome = 'JÉSSICA OLIVEIRA CARNEIRO' where matricula - 000288 = 0;
update aluno set nome = 'MARIA EDUARDA SILVA MAIA' where matricula - 000259 = 0;
update aluno set nome = 'YURI COSTA MARQUES RIBEIRO' where matricula - 000250 = 0;
update aluno set nome = 'LUCAS KAUÃ FERREIRA MONTEIRO' where matricula - 000267 = 0;
update aluno set nome = 'RENAN SANTOS LOPES' where matricula - 000104 = 0;
update aluno set nome = 'SAN-DIEGO MACIEL MARTINS' where matricula - 000125 = 0;
update aluno set nome = 'RAFAEL MARINHO DE SOUZA' where matricula - 000028 = 0;
update aluno set nome = 'MARCO TÚLIO TEIXEIRA DE ANDRADE' where matricula - 000573 = 0;
update aluno set nome = 'PÂMELA LETÍCIA MARTINS MIRANDA' where matricula - 000156 = 0;
update aluno set nome = 'ANA CLARA CAETANO BARBOSA' where matricula - 000261 = 0;
update aluno set nome = 'ANA JULIA ABREU GONÇALVES' where matricula - 000166 = 0;
update aluno set nome = 'ANDRY HENRIQUE SIQUEIRA BARBOSA' where matricula - 000256 = 0;
update aluno set nome = 'BIANCA DE ANDRADE JALES' where matricula - 000019 = 0;
update aluno set nome = 'FRANCISCO NEVES NAVARRO DE OLIVEIRA' where matricula - 000140 = 0;
update aluno set nome = 'JOANA D\'ARC ALVES DE SOUZA' where matricula - 000236 = 0;
update aluno set nome = 'JOÃO PEDRO MIRANDA DE SOUZA' where matricula - 000272 = 0;
update aluno set nome = 'KAROLYNE APARECIDA FERREIRA DOS SANTOS' where matricula - 000257 = 0;
update aluno set nome = 'KAUÊ RIBEIRO FELIX DIAS' where matricula - 000215 = 0;
update aluno set nome = 'LUCAS RAFAEL MOREIRA DA SILVA' where matricula - 000161 = 0;
update aluno set nome = 'MARIA EDUARDA LOPES MOURA' where matricula - 000183 = 0;
update aluno set nome = 'RANGEL SARAIVA BRAGA' where matricula - 000315 = 0;
update aluno set nome = 'ISADORA PIETRA OLIVEIRA CHAGAS' where matricula - 000316 = 0;
update aluno set nome = 'VICTOR RODRIGUES FIGUEIREDO' where matricula - 000133 = 0;
update aluno set nome = 'GUILHERME LIMA DE SOUZA CHAVES' where matricula - 000046 = 0;
update aluno set nome = 'SAMUEL WILLIAM ALVES DE SOUZA' where matricula - 000018 = 0;
update aluno set nome = 'ANA CAROLINA DE BARROS SILVA' where matricula - 000247 = 0;
update aluno set nome = 'GABRIEL JUNIO MACIEL LIMA' where matricula - 000108 = 0;
update aluno set nome = 'LUIZ OTÁVIO DE LIMA GONÇALVES' where matricula - 000012 = 0;
update aluno set nome = 'MARIA PAULA SILVA DO CARMO' where matricula - 000214 = 0;
update aluno set nome = 'RAFAEL VIEIRA SILVA' where matricula - 000321 = 0;
update aluno set nome = 'SAMUEL COUTINHO PEREIRA' where matricula - 000304 = 0;
update aluno set nome = 'CAIO HENRIQUE FERREIRA REIS' where matricula - 000249 = 0;
update aluno set nome = 'JULLIA CASSIANE VEIGA SILVA' where matricula - 000248 = 0;
update aluno set nome = 'RIAN WENDER DE SOUZA SILVA' where matricula - 000039 = 0;
update aluno set nome = 'SAMUEL BARBOSA DA SILVA' where matricula - 000262 = 0;
update aluno set nome = 'VIVIANE CRISTINA TOMAZ TEIXEIRA' where matricula - 000147 = 0;
update aluno set nome = 'LUÍS OTÁVIO PEREIRA DA CONCEIÇÃO' where matricula - 000055 = 0;
update aluno set nome = 'ALINE BARBOSA MOREIRA' where matricula - 000323 = 0;
update aluno set nome = 'ANNA JÚLIA VALADARES DE OLIVEIRA' where matricula - 000314 = 0;
update aluno set nome = 'JOÃO VÍTOR CORRÊA DA SILVA' where matricula - 000298 = 0;
update aluno set nome = 'KAUAN MACHADO FREITAS' where matricula - 000210 = 0;
update aluno set nome = 'KAUANE GABRIELE ALVES COSTA' where matricula - 000173 = 0;
update aluno set nome = 'PIÊTRA GONÇALVES SATURNINO' where matricula - 000159 = 0;
update aluno set nome = 'YASMIN JULIA DE CARVALHO PEREIRA' where matricula - 000205 = 0;
update aluno set nome = 'EMILY VITORIA COELHO CARVALHO' where matricula - 000015 = 0;
update aluno set nome = 'CARLA JASMIM DE LIMA SILVA' where matricula - 000033 = 0;
update aluno set nome = 'LETÍCIA LIMA DE SOUZA CHAVES' where matricula - 000044 = 0;
update aluno set nome = 'ANA CAROLINA GUILHERME DE SOUZA' where matricula - 000110 = 0;
update aluno set nome = 'ANDREZA GONÇALVES DA SILVA LIMA' where matricula - 000093 = 0;
update aluno set nome = 'DANIELLA DAFNE OLIVEIRA FELICIANO' where matricula - 000131 = 0;
update aluno set nome = 'DANILO SILVA MOREIRA' where matricula - 000300 = 0;
update aluno set nome = 'GRAZIELLA ARAÚJO MENDES' where matricula - 000310 = 0;
update aluno set nome = 'LIS STEFANY DA COSTA DINIZ' where matricula - 000285 = 0;
update aluno set nome = 'LORENA VITÓRIA DOS SANTOS COELHO' where matricula - 000313 = 0;
update aluno set nome = 'LUCAS BARBOSA TORRES' where matricula - 000233 = 0;
update aluno set nome = 'MARCELA PEREIRA TEIXEIRA' where matricula - 000097 = 0;
update aluno set nome = 'NETHALY DE JESUS GONÇALVES' where matricula - 000282 = 0;
update aluno set nome = 'VINÍCIUS EDUARDO DA SILVA E ROSA' where matricula - 000303 = 0;
update aluno set nome = 'ARTHUR EDUARDO GONÇALVES SANTOS' where matricula - 000188 = 0;
update aluno set nome = 'CECÍLIA NYCOLLE RIBEIRO SOUZA' where matricula - 000275 = 0;
update aluno set nome = 'ERIK FABIEL FERREIRA MONTEIRO' where matricula - 000266 = 0;
update aluno set nome = 'GUILHERME HENRIQUE MERCES LOURENCO' where matricula - 000146 = 0;
update aluno set nome = 'KAIQUE ÂNGELO MARQUES DE SOUZA' where matricula - 000217 = 0;
update aluno set nome = 'LUCAS ARAUJO OLIVEIRA' where matricula - 000307 = 0;
update aluno set nome = 'MARCUS VINÍCIUS FREITAS SOARES' where matricula - 000191 = 0;
update aluno set nome = 'PABLO EDUARDO TEIXEIRA RODRIGUES' where matricula - 000312 = 0;
update aluno set nome = 'VITÓRIA ISABELLE RODRIGUES DE ALMEIDA' where matricula - 000220 = 0;
update aluno set nome = 'ANA LUIZA SILVA PEREIRA' where matricula - 000286 = 0;
update aluno set nome = 'DAVID MIGUEL ALMEIDA MARQUES SILVEIRA' where matricula - 000279 = 0;
update aluno set nome = 'DANIEL AUGUSTO BARBOSA DA SILVA' where matricula - 000069 = 0;
update aluno set nome = 'EDUARDA MARTINS DE SOUZA' where matricula - 000284 = 0;
update aluno set nome = 'ERIK NUNES MACHADO' where matricula - 000092 = 0;
update aluno set nome = 'GIOVANNA EMANUELLE RODRIGUES DE OLIVEIRA' where matricula - 000204 = 0;
update aluno set nome = 'JOÃO VICTOR DE OLIVEIRA COSTA' where matricula - 000296 = 0;
update aluno set nome = 'MARINA CAETANO CHAGAS' where matricula - 000271 = 0;
update aluno set nome = 'MAURO PATRICK FERREIRA RODRIGUES' where matricula - 000268 = 0;
update aluno set nome = 'OTÁVIO MIRANDA OLIVEIRA' where matricula - 000187 = 0;
update aluno set nome = 'PEDRO HENRIQUE ALEXANDRE SILVA' where matricula - 000185 = 0;
update aluno set nome = 'RAYSSA ANTÔNIA DOS REIS ARAÚJO' where matricula - 000222 = 0;
update aluno set nome = 'YASMIN LUANE DE OLIVEIRA CARDOSO' where matricula - 000203 = 0;
update aluno set nome = 'DAVI ELIAS MARTINS SILVA' where matricula - 000276 = 0;
update aluno set nome = 'EDUARDO MARQUES BONFIM' where matricula - 000306 = 0;
update aluno set nome = 'JOHNNY ALVES DE OLIVEIRA' where matricula - 000127 = 0;
update aluno set nome = 'MARIA CLARA DE PAULA VIEIRA' where matricula - 000123 = 0;
update aluno set nome = 'TAYNARA ALINE GOMES DOS SANTOS' where matricula - 000225 = 0;
update aluno set nome = 'RAÍSSA BIANCA BARBOSA DA SILVA' where matricula - 000034 = 0;
update aluno set nome = 'LUANA BARBOSA TORRES' where matricula - 000231 = 0;
update aluno set nome = 'MARCUS CLÁUDIO FERNANDES DE OLIVEIRA GOULART' where matricula - 000270 = 0;
update aluno set nome = 'MARIA EDUARDA VIEIRA MARÇAL' where matricula - 000139 = 0;
update aluno set nome = 'MATHEUS HENRIQUE DA COSTA BALDEZ' where matricula - 000168 = 0;
update aluno set nome = 'NATÁLIA PEREIRA DE ALMEIDA' where matricula - 000117 = 0;
update aluno set nome = 'GABRIELLE VIEIRA SILVA' where matricula - 000230 = 0;
update aluno set nome = 'JULIA LARA SILVA VIDA' where matricula - 000199 = 0;
update aluno set nome = 'RAFAEL AVELAR OLIVEIRA' where matricula - 000030 = 0;
update aluno set nome = 'GABRIEL MARINHO DE SOUZA' where matricula - 000031 = 0;
update aluno set nome = 'LUÍS FILIPE ALVES AQUINO' where matricula - 000043 = 0;
update aluno set nome = 'WENDER MATEUS PEREIRA DE OLIVEIRA' where matricula - 000551 = 0;
update aluno set nome = 'ANNA GABRIELLE COSTA RODRIGUES TOMÉ' where matricula - 000623 = 0;
update aluno set nome = 'CRISTIELE LOPES GONÇALVES RESENDE' where matricula - 000277 = 0;
update aluno set nome = 'DÉBORA EDUARDA DOS SANTOS BARBOSA' where matricula - 000283 = 0;
update aluno set nome = 'LARISSA SOARES MENDES' where matricula - 000129 = 0;
update aluno set nome = 'LEONARDO SILVA GONÇALVES' where matricula - 000311 = 0;
update aluno set nome = 'LUISA GOMES OLIVEIRA' where matricula - 000136 = 0;
update aluno set nome = 'MARIA EDUARDA DA SILVA' where matricula - 000308 = 0;
update aluno set nome = 'MARIA ELOÍSA DE OLIVEIRA CHAGAS' where matricula - 000189 = 0;
update aluno set nome = 'PEDRO LUÍS GONÇALVES DOMINGOS' where matricula - 000305 = 0;
update aluno set nome = 'RAYSSA MIRANDA SANTOS' where matricula - 000032 = 0;
update aluno set nome = 'MARIA EDUARDA DA COSTA DIAS' where matricula - 000320 = 0;
update aluno set nome = 'MARIA LUIZA RATES LOUZADA BARBOSA' where matricula - 000309 = 0;
update aluno set nome = 'VICTOR SAMUEL LACERDA RODRIGUES' where matricula - 000272 = 0;
update aluno set nome = 'PEDRO HENRIQUE SOARES CARNEIRO' where matricula - 000516 = 0;
update aluno set nome = 'ANDRÉ LUÍS MARTINS MAIA' where matricula - 000409 = 0;
update aluno set nome = 'GIOVANNA DE OLIVEIRA LIMA' where matricula - 000417 = 0;
update aluno set nome = 'LAYSA EDUARDA OLIMPIO SOARES' where matricula - 000416 = 0;
update aluno set nome = 'ANA CLARA GOMES OLIVEIRA' where matricula - 000400 = 0;
update aluno set nome = 'ANA LUÍSA DE CARVALHO SILVEIRA' where matricula - 000566 = 0;
update aluno set nome = 'GABRIEL HENRIQUE MOURA' where matricula - 000423 = 0;
update aluno set nome = 'GIOVANNA ISABELLE DE OLIVEIRA CARDOSO' where matricula - 000407 = 0;
update aluno set nome = 'GUSTAVO HENRIQUE ARAÚJO' where matricula - 000452 = 0;
update aluno set nome = 'HÉLIK CORDEIRO COSTA' where matricula - 000487 = 0;
update aluno set nome = 'KAUÃ GABRIEL MAGALHÃES BUERI MARTINS' where matricula - 000426 = 0;
update aluno set nome = 'PEDRO HENRIQUE MENDES DA SILVA' where matricula - 000432 = 0;
update aluno set nome = 'CAMILA ALESSANDRA DUARTE' where matricula - 000570 = 0;
update aluno set nome = 'KEYSSE PRISCILA OLIVEIRA SILVA' where matricula - 000631 = 0;
update aluno set nome = 'SAMUEL FERNANDES FERREIRA' where matricula - 000425 = 0;
update aluno set nome = 'MARCOS LIMA FARIA' where matricula - 000477 = 0;
update aluno set nome = 'ANA CLARA DE LIMA SERRA BARRENSE' where matricula - 000476 = 0;
update aluno set nome = 'ISABELLA DE AZEVEDO COELHO' where matricula - 000446 = 0;
update aluno set nome = 'PAOLA VÍTOR RODRIGUES' where matricula - 000473 = 0;
update aluno set nome = 'GIOVANNA LETÍCIA TEIXEIRA DOS SANTOS' where matricula - 000457 = 0;
update aluno set nome = 'ANNA JULIA ALVES AQUINO' where matricula - 000454 = 0;
update aluno set nome = 'JOÃO PAULO LAWALL COSTA' where matricula - 000545 = 0;
update aluno set nome = 'ARTHUR EDUARDO SILVA ALVES' where matricula - 000564 = 0;
update aluno set nome = 'CAIO CAMPOS VALADARES' where matricula - 000550 = 0;
update aluno set nome = 'FRANCIELE LOPES GONÇALVES RESENDE' where matricula - 000527 = 0;
update aluno set nome = 'JOÃO ROBERTO PEREIRA DOS REIS' where matricula - 000565 = 0;
update aluno set nome = 'LISLEY EDUARDA DA SILVA OLIVEIRA' where matricula - 000435 = 0;
update aluno set nome = 'LUAN BARBOSA SILVA CUNHA' where matricula - 000559 = 0;
update aluno set nome = 'LUANA DE CÁSSIA REIS GOMES' where matricula - 000483 = 0;
update aluno set nome = 'SARA EMANUELE SILVA MARQUES' where matricula - 000429 = 0;
update aluno set nome = 'ARTHUR HENRIQUE MORAIS COSTA' where matricula - 000493 = 0;
update aluno set nome = 'RANIELL LURRANE DOS REIS FLOR' where matricula - 000492 = 0;
update aluno set nome = 'VITÓRIA LUIZA SILVA SANTOS' where matricula - 000439 = 0;
update aluno set nome = 'KEROLLAY ALVES SANTIAGO' where matricula - 000505 = 0;
update aluno set nome = 'PEDRO PAULO NASCIMENTO JUNIOR' where matricula - 000547 = 0;
update aluno set nome = 'BEATRIZ SANTOS DE ALMEIDA' where matricula - 000648 = 0;
update aluno set nome = 'CARLA QUIRINA PEREIRA' where matricula - 000567 = 0;
update aluno set nome = 'GABRIEL TEIXEIRA ALVARENGA' where matricula - 000537 = 0;
update aluno set nome = 'JOÃO PAULO WAGNER MONTEIRO DO AMARAL' where matricula - 000499 = 0;
update aluno set nome = 'PATRICK DIAS LOPES' where matricula - 000489 = 0;
update aluno set nome = 'JOÃO GUILHERME GOMES DE PAULA' where matricula - 000513 = 0;
update aluno set nome = 'CAROLINA CARDOSO SOARES' where matricula - 000555 = 0;
update aluno set nome = 'EDUARDO JÚNIO SILVA SANTOS' where matricula - 000436 = 0;
update aluno set nome = 'LETHÍCIA GONÇALVES MARTINS' where matricula - 000533 = 0;
update aluno set nome = 'DANIEL OLIVEIRA DE FARIA' where matricula - 000518 = 0;
update aluno set nome = 'CLARA GOMES ASSIS' where matricula - 000723 = 0;
update aluno set nome = 'MACLAUS CAMPOS CELESTINO' where matricula - 000706 = 0;
update aluno set nome = 'LETÍCIA APARECIDA MACHADO VIEIRA' where matricula - 000703 = 0;
update aluno set nome = 'MARCO ANTÔNIO DE SOUZA LOPES' where matricula - 000739 = 0;
update aluno set nome = 'JENNIFER BRENDA COSTA RODRIGUES TOMÉ' where matricula - 000626 = 0;
update aluno set nome = 'ANA CAROLINA OLIVEIRA DA SILVA' where matricula - 000725 = 0;
update aluno set nome = 'JÚLIA SILVA MAXIMO' where matricula - 000749 = 0;
update aluno set nome = 'ANA CAROLINA LOURENÇO MALTHIK' where matricula - 000643 = 0;
update aluno set nome = 'MARIA EDUARDA RODRIGUES PINHO' where matricula - 000721 = 0;
update aluno set nome = 'NATÁLIA MATOS DE OLIVEIRA' where matricula - 000656 = 0;
update aluno set nome = 'STÉPHANY CAROLINE COSTA RODRIGUES TOMÉ' where matricula - 000628 = 0;
